['Landscape architecture', 'Landscape design'],
['Applied ethics', 'Animal rights'],
['Applied ethics', 'Bioethics'],
['Applied ethics', 'Environmental ethics'],
['Normative ethics', 'Virtue ethics'],
['Philosophy of mind', 'Philosophy of pain'],
['Philosophy of mind', 'Philosophy of artificial intelligence'],
['Philosophy of mind', 'Philosophy of perception'],
['Christian theology', 'Anglican theology'],
['Christian theology', 'Baptist theology'],
['Christian theology', 'Catholic theology'],
['Christian theology', 'Eastern Orthodox theology'],
['Christian theology', 'Protestant theology'],
['Machine Learning', 'Artificial neural network'],
['Machine Learning', 'Support vector machine'],
['Programming Paradigms', 'Concurrent programming'],
['Programming Paradigms', 'Functional programming'],
['Programming Paradigms', 'Imperative programming'],
['Programming Paradigms', 'Logic programming'],
['Programming Paradigms', 'Object-oriented programming'],
['Category theory', 'Topos theory'],
['Group theory', 'Group representation'],
['Ring theory', 'Commutative algebra'],
['Ring theory', 'Noncommutative algebra'],
['Functional analysis', 'Operator theory'],
['Harmonic analysis', 'Fourier analysis'],
['Real analysis', 'Calculus (outline)'],
['Measure theory', 'Integral geometry'],
['Quantum gravity', 'String theory'],
['Landscape architecture', 'Landscape planning'],
['Conducting', 'Choral conducting'],
['Conducting', 'Orchestral conducting'],
['Conducting', 'Wind ensemble conducting'],
['Musicology', 'Historical musicology'],
['Musicology', 'Systematic musicology'],
['Organology', 'Organ and historical keyboards'],
['Organology', 'Piano'],
['Organology', 'Strings, harp, oud, and guitar (outline)'],
['Organology', 'Singing'],
['Organology', 'Woodwinds, brass, and percussion'],
['Graphic Arts', 'Drawing (outline)'],
['Graphic Arts', 'Painting (outline)'],
['Graphic Arts', 'Photography (outline)'],
['Architecture (Outline of architecture)', 'Interior architecture'],
['Architecture (Outline of architecture)', 'Landscape architecture'],
['Architecture (Outline of architecture)', 'Architectural analytics'],
['Architecture (Outline of architecture)', 'Historic preservation'],
['Architecture (Outline of architecture)', 'Interior design (interior architecture)'],
['Architecture (Outline of architecture)', 'Technical drawing'],
['Medieval philosophy', 'Humanism (outline)'],
['Medieval philosophy', 'Scholasticism'],
['International law', 'Public international law'],
['International law', 'Supranational law'],
['Criminal procedure', 'Forensic science (outline)'],
['Criminal procedure', 'Police science'],
['Philosophy of physical sciences', 'Philosophy of biology'],
['Philosophy of physical sciences', 'Philosophy of chemistry'],
['Philosophy of physical sciences', 'Philosophy of physics'],
['Epistemology (outline)', 'Justification'],
['Epistemology (outline)', 'Reasoning errors'],
['Ethics (outline)', 'Applied ethics'],
['Ethics (outline)', 'Meta-ethics'],
['Ethics (outline)', 'Moral psychology, Descriptive ethics, Value theory'],
['Ethics (outline)', 'Normative ethics'],
['Logic (outline)', 'Mathematical logic'],
['Logic (outline)', 'Philosophical logic'],
['Metaphysics (outline)', 'Philosophy of Action'],
['Metaphysics (outline)', 'Determinism and Free will'],
['Metaphysics (outline)', 'Ontology'],
['Metaphysics (outline)', 'Philosophy of mind'],
['Metaphysics (outline)', 'Philosophy of space and time'],
['Metaphysics (outline)', 'Teleology'],
['Metaphysics (outline)', 'Theism and Atheism'],
['Philosophical traditions and schools', 'African philosophy'],
['Philosophical traditions and schools', 'Analytic philosophy'],
['Philosophical traditions and schools', 'Aristotelianism'],
['Philosophical traditions and schools', 'Continental philosophy'],
['Philosophical traditions and schools', 'Eastern philosophy'],
['Philosophical traditions and schools', 'Feminist philosophy'],
['Philosophical traditions and schools', 'Platonism'],
['Social philosophy and political philosophy', 'Anarchism (outline)'],
['Social philosophy and political philosophy', 'Feminist philosophy'],
['Social philosophy and political philosophy', 'Libertarianism (outline)'],
['Social philosophy and political philosophy', 'Marxism'],
['Theology', 'Biblical studies'],
['Theology', 'Religious studies'],
['Theology', 'Biblical Hebrew, Biblical Greek, Aramaic'],
['Theology', 'Buddhist theology'],
['Theology', 'Christian theology'],
['Theology', 'Hindu theology'],
['Theology', 'Jewish theology'],
['Theology', 'Muslim theology'],
['American studies', 'Appalachian studies'],
['American studies', 'Canadian studies'],
['American studies', 'Latin American studies'],
['Asian studies', 'Central Asian studies'],
['Asian studies', 'East Asian studies'],
['Asian studies', 'Indology'],
['Asian studies', 'Iranian studies'],
['Asian studies', 'Japanese studies'],
['Asian studies', 'Korean studies'],
['Asian studies', 'Pakistan studies'],
['Asian studies', 'Sindhology'],
['Asian studies', 'Sinology (outline)'],
['Asian studies', 'Southeast Asian studies'],
['Asian studies', 'Thai studies'],
['European studies', 'Celtic studies'],
['European studies', 'German studies'],
['European studies', 'Sociology in Poland'],
['European studies', 'Scandinavian studies'],
['European studies', 'Slavic studies'],
['Middle Eastern studies', 'Arab studies'],
['Middle Eastern studies', 'Assyriology'],
['Middle Eastern studies', 'Egyptology'],
['Middle Eastern studies', 'Jewish studies'],
['Economic sociology/Socioeconomics', 'Economic development'],
['Economic sociology/Socioeconomics', 'Social development'],
['Entomology', 'Forensic entomology'],
['Malacology', 'Conchology'],
['Paleontology', 'Paleobiology'],
['Paleontology', 'Paleoecology'],
['Observational astronomy', 'Gamma ray astronomy'],
['Observational astronomy', 'Infrared astronomy'],
['Observational astronomy', 'Microwave astronomy'],
['Observational astronomy', 'Optical astronomy'],
['Observational astronomy', 'Radio astronomy'],
['Observational astronomy', 'UV astronomy'],
['Observational astronomy', 'X-ray astronomy'],
['Gravitational astronomy', 'Black holes'],
['Multi-valued logic', 'Fuzzy logic'],
['Cognitive science', 'Automated reasoning'],
['Cognitive science', 'Computer vision (outline)'],
['Cognitive science', 'Machine learning'],
['Cognitive science', 'Natural language processing (Computational linguistics)'],
['Computer-aided engineering', 'Computational fluid dynamics'],
['Computer-aided engineering', 'Finite element analysis'],
['Database (outline)', 'Distributed database'],
['Database (outline)', 'Object database'],
['Database (outline)', 'Relational database'],
['Multimedia, hypermedia', 'Sound and music computing'],
['Distributed computing', 'Grid computing'],
['Parallel computing', 'High-performance computing'],
['Programming languages', 'Compilers'],
['Programming languages', 'Programming paradigms'],
['Programming languages', 'Program semantics'],
['Programming languages', 'Type theory'],
['Software engineering', 'Formal methods (Formal verification)'],
['Theory of computation', 'Automata theory (Formal languages)'],
['Theory of computation', 'Computability theory'],
['Theory of computation', 'Computational complexity theory'],
['Theory of computation', 'Concurrency theory'],
['Mathematical logic and Foundations of mathematics', 'Intuitionistic logic'],
['Mathematical logic and Foundations of mathematics', 'Modal logic'],
['Mathematical logic and Foundations of mathematics', 'Model theory'],
['Mathematical logic and Foundations of mathematics', 'Proof theory'],
['Mathematical logic and Foundations of mathematics', 'Recursion theory'],
['Mathematical logic and Foundations of mathematics', 'Set theory'],
['Algebra (outline)', 'Associative algebra'],
['Algebra (outline)', 'Category theory'],
['Algebra (outline)', 'Differential algebra'],
['Algebra (outline)', 'Field theory'],
['Algebra (outline)', 'Group theory'],
['Algebra (outline)', 'Homological algebra'],
['Algebra (outline)', 'K-theory'],
['Algebra (outline)', 'Lattice theory (Order theory)'],
['Algebra (outline)', 'Lie algebra'],
['Algebra (outline)', 'Linear algebra (Vector space)'],
['Algebra (outline)', 'Multilinear algebra'],
['Algebra (outline)', 'Non-associative algebra'],
['Algebra (outline)', 'Representation theory'],
['Algebra (outline)', 'Ring theory'],
['Algebra (outline)', 'Universal algebra'],
['Analysis', 'Complex analysis'],
['Analysis', 'Functional analysis'],
['Analysis', 'Harmonic analysis'],
['Analysis', 'Non-standard analysis'],
['Analysis', 'Ordinary differential equations'],
['Analysis', 'p-adic analysis'],
['Analysis', 'Partial differential equations'],
['Analysis', 'Real analysis'],
['Probability theory', 'Ergodic theory'],
['Probability theory', 'Measure theory'],
['Probability theory', 'Stochastic process'],
['Geometry (outline) and Topology', 'Affine geometry'],
['Geometry (outline) and Topology', 'Algebraic geometry'],
['Geometry (outline) and Topology', 'Algebraic topology'],
['Geometry (outline) and Topology', 'Convex geometry'],
['Geometry (outline) and Topology', 'Differential topology'],
['Geometry (outline) and Topology', 'Discrete geometry'],
['Geometry (outline) and Topology', 'Finite geometry'],
['Geometry (outline) and Topology', 'Galois geometry'],
['Geometry (outline) and Topology', 'General topology'],
['Geometry (outline) and Topology', 'Geometric topology'],
['Geometry (outline) and Topology', 'Integral geometry'],
['Geometry (outline) and Topology', 'Noncommutative geometry'],
['Geometry (outline) and Topology', 'Non-Euclidean geometry'],
['Geometry (outline) and Topology', 'Projective geometry'],
['Number theory', 'Algebraic number theory'],
['Number theory', 'Analytic number theory'],
['Number theory', 'Arithmetic combinatorics'],
['Number theory', 'Geometric number theory'],
['Combinatorics (outline)', 'Coding theory'],
['Dynamical systems', 'Chaos theory'],
['Dynamical systems', 'Fractal geometry'],
['Mathematical physics', 'Quantum field theory'],
['Mathematical physics', 'Quantum gravity'],
['Mathematical physics', 'Quantum mechanics'],
['Mathematical physics', 'Statistical mechanics'],
['Operations research', 'Assignment problem'],
['Operations research', 'Decision analysis'],
['Operations research', 'Dynamic programming'],
['Operations research', 'Inventory theory'],
['Operations research', 'Linear programming'],
['Operations research', 'Mathematical optimization'],
['Operations research', 'Optimal maintenance'],
['Operations research', 'Real options analysis'],
['Operations research', 'Scheduling'],
['Operations research', 'Stochastic processes'],
['Operations research', 'Systems analysis'],
['Statistics (outline)', 'Actuarial science'],
['Statistics (outline)', 'Demography'],
['Statistics (outline)', 'Econometrics'],
['Statistics (outline)', 'Mathematical statistics'],
['Statistics (outline)', 'Data visualization'],
['', 'Computational complexity theory'],
['Bioengineering', 'Biochemical engineering'],
['Bioengineering', 'Biomolecular engineering'],
['Process design', 'Petroleum engineering'],
['Process design', 'Nuclear engineering'],
['Process design', 'Food engineering'],
['Geotechnical engineering', 'Engineering geology'],
['Transportation engineering', 'Highway engineering'],
['Structural engineering', 'Architectural engineering'],
['Control systems engineering', 'Control theory'],
['Electronic engineering', 'Instrumentation engineering'],
['Engineering physics', 'Photonics'],
['Aerospace engineering', 'Aeronautics'],
['Aerospace engineering', 'Astronautics'],
['Biomedical engineering', 'Biomechanical engineering'],
['Biomedical engineering', 'Neural engineering'],
['Control theory', 'Affect control theory'],
['Control theory', 'Control engineering'],
['Control theory', 'Control systems'],
['Control theory', 'Dynamical systems'],
['Control theory', 'Perceptual control theory'],
['Cybernetics', 'Biocybernetics'],
['Cybernetics', 'Engineering cybernetics'],
['Cybernetics', 'Management cybernetics'],
['Cybernetics', 'Medical cybernetics'],
['Cybernetics', 'New Cybernetics'],
['Cybernetics', 'Second-order cybernetics'],
['Cybernetics', 'Sociocybernetics'],
['Computational systems biology', 'Synthetic biology'],
['Computational systems biology', 'Systems immunology'],
['Computational systems biology', 'Systems neuroscience'],
['System dynamics', 'Social dynamics'],
['Systems ecology', 'Ecosystem ecology'],
['Systems engineering', 'Biological systems engineering'],
['Systems engineering', 'Earth systems engineering and management'],
['Systems engineering', 'Enterprise systems engineering'],
['Systems engineering', 'Systems analysis'],
['Systems psychology', 'Ergonomics'],
['Systems psychology', 'Family systems theory'],
['Systems psychology', 'Systemic therapy'],
['Systems theory', 'Biochemical systems theory'],
['Systems theory', 'Ecological systems theory'],
['Systems theory', 'Developmental systems theory'],
['Systems theory', 'General systems theory'],
['Systems theory', 'Living systems theory'],
['Systems theory', 'LTI system theory'],
['Systems theory', 'Mathematical system theory'],
['Systems theory', 'Sociotechnical systems theory'],
['Systems theory', 'World-systems theory'],
['Cardiology', 'Cardiac electrophysiology'],
['Music', 'Accompanying'],
['Music', 'Chamber music'],
['Music', 'Church music'],
['Music', 'Conducting'],
['Music', 'Early music'],
['Music', 'Jazz studies (outline)'],
['Music', 'Musical composition'],
['Music', 'Music education'],
['Music', 'Music history'],
['Music', 'Musicology'],
['Music', 'Ethnomusicology'],
['Music', 'Music theory'],
['Music', 'Orchestral studies'],
['Music', 'Organology'],
['Music', 'Recording'],
['Dance', 'Choreography'],
['Dance', 'Dance notation'],
['Dance', 'Ethnochoreology'],
['Dance', 'History of dance'],
['Television (outline)', 'Television studies'],
['Theatre (outline)', 'Acting'],
['Theatre (outline)', 'Directing'],
['Theatre (outline)', 'Dramaturgy'],
['Theatre (outline)', 'History'],
['Theatre (outline)', 'Musical theatre'],
['Theatre (outline)', 'Playwrighting'],
['Theatre (outline)', 'Puppetry'],
['Theatre (outline)', 'Scenography'],
['Theatre (outline)', 'Stage design'],
['Theatre (outline)', 'Ventriloquism'],
['Film (outline)', 'Animation'],
['Film (outline)', 'Film criticism'],
['Film (outline)', 'Filmmaking'],
['Film (outline)', 'Film theory'],
['Film (outline)', 'Live action'],
['Fine Arts', 'Graphic Arts'],
['Fine Arts', 'Sculpture'],
['Applied arts', 'Animation'],
['Applied arts', 'Calligraphy'],
['Applied arts', 'Decorative arts'],
['Applied arts', 'Mixed media'],
['Applied arts', 'Printmaking'],
['Applied arts', 'Studio art'],
['Applied arts', 'Architecture (Outline of architecture)'],
['Applied arts', 'Fashion'],
['Ancient history', 'Ancient Egypt'],
['Ancient history', 'Carthage'],
['Ancient history', 'Ancient Greek history (outline)'],
['Ancient history', 'Ancient Roman history (outline)'],
['Ancient history', 'Assyrian Civilization'],
['Ancient history', 'Bronze Age Civilizations'],
['Ancient history', 'Biblical history'],
['Ancient history', 'History of the Indus Valley Civilization'],
['Ancient history', 'Preclassic Maya'],
['Ancient history', 'History of Mesopotamia'],
['Ancient history', 'The Stone Age'],
['Ancient history', 'History of the Yangtze civilization'],
['Ancient history', 'History of the Yellow River civilization'],
['Asian history', 'Chinese history'],
['Asian history', 'Indian history (outline)'],
['Asian history', 'Indonesian history'],
['Asian history', 'Iranian history'],
['History of philosophy', 'Ancient philosophy'],
['History of philosophy', 'Contemporary philosophy'],
['History of philosophy', 'Medieval philosophy'],
['History of philosophy', 'Modern philosophy'],
['Linguistics (Outline of linguistics)', 'Applied linguistics'],
['Linguistics (Outline of linguistics)', 'Composition studies'],
['Linguistics (Outline of linguistics)', 'Computational linguistics'],
['Linguistics (Outline of linguistics)', 'Discourse analysis'],
['Linguistics (Outline of linguistics)', 'English studies'],
['Linguistics (Outline of linguistics)', 'Etymology'],
['Linguistics (Outline of linguistics)', 'Grammar'],
['Linguistics (Outline of linguistics)', 'Grammatology'],
['Linguistics (Outline of linguistics)', 'Historical linguistics'],
['Linguistics (Outline of linguistics)', 'History of linguistics'],
['Linguistics (Outline of linguistics)', 'Interlinguistics'],
['Linguistics (Outline of linguistics)', 'Lexicology'],
['Linguistics (Outline of linguistics)', 'Linguistic typology'],
['Linguistics (Outline of linguistics)', 'Morphology (linguistics)'],
['Linguistics (Outline of linguistics)', 'Natural language processing'],
['Linguistics (Outline of linguistics)', 'Philology'],
['Linguistics (Outline of linguistics)', 'Phonetics'],
['Linguistics (Outline of linguistics)', 'Phonology'],
['Linguistics (Outline of linguistics)', 'Pragmatics'],
['Linguistics (Outline of linguistics)', 'Psycholinguistics'],
['Linguistics (Outline of linguistics)', 'Rhetoric'],
['Linguistics (Outline of linguistics)', 'Semantics'],
['Linguistics (Outline of linguistics)', 'Semiotics (outline)'],
['Linguistics (Outline of linguistics)', 'Sociolinguistics'],
['Linguistics (Outline of linguistics)', 'Syntax'],
['Linguistics (Outline of linguistics)', 'Usage'],
['Linguistics (Outline of linguistics)', 'Word usage'],
['Creative writing', 'Fiction (outline)'],
['Creative writing', 'Non-fiction'],
['History of literature', 'Ancient literature'],
['History of literature', 'Medieval literature'],
['History of literature', 'Post-colonial literature'],
['History of literature', 'Post-modern literature'],
['History of literature', 'Critical theory (outline)'],
['History of literature', 'Literary criticism'],
['History of literature', 'Poetics'],
['World literature', 'African-American literature'],
['World literature', 'American literature'],
['World literature', 'British literature'],
['Civil law', 'Admiralty law'],
['Civil law', 'Animal law/Animal rights'],
['Civil law', 'Civil procedure'],
['Civil law', 'Common law'],
['Civil law', 'Contract law'],
['Civil law', 'Corporations'],
['Civil law', 'Environmental law'],
['Civil law', 'Family law'],
['Civil law', 'Federal law'],
['Civil law', 'International law'],
['Civil law', 'Labor law'],
['Civil law', 'Property law'],
['Civil law', 'Tax law'],
['Civil law', 'Tort law (outline)'],
['Criminal law', 'Criminal justice (outline)'],
['Criminal law', 'Criminal procedure'],
['Legal management', 'Commercial law'],
['Legal management', 'Corporate law'],
['Applied philosophy', 'Philosophy of economics'],
['Applied philosophy', 'Philosophy of education'],
['Applied philosophy', 'Philosophy of engineering'],
['Applied philosophy', 'Philosophy of history'],
['Applied philosophy', 'Philosophy of language'],
['Applied philosophy', 'Philosophy of law'],
['Applied philosophy', 'Philosophy of mathematics'],
['Applied philosophy', 'Philosophy of music'],
['Applied philosophy', 'Philosophy of psychology'],
['Applied philosophy', 'Philosophy of religion'],
['Applied philosophy', 'Philosophy of physical sciences'],
['Applied philosophy', 'Philosophy of social science'],
['Applied philosophy', 'Philosophy of technology'],
['Applied philosophy', 'Systems philosophy'],
['Applied philosophy', 'Epistemology (outline)'],
['Applied philosophy', 'Ethics (outline)'],
['Applied philosophy', 'Logic (outline)'],
['Applied philosophy', 'Meta-philosophy'],
['Applied philosophy', 'Metaphysics (outline)'],
['Applied philosophy', 'Philosophical traditions and schools'],
['Applied philosophy', 'Social philosophy and political philosophy'],
['Applied philosophy', 'Theology'],
['Physical geography', 'Atmology'],
['Physical geography', 'Biogeography'],
['Physical geography', 'Climatology'],
['Physical geography', 'Coastal geography'],
['Physical geography', 'Emergency management'],
['Physical geography', 'Environmental geography'],
['Physical geography', 'Geobiology'],
['Physical geography', 'Geochemistry'],
['Physical geography', 'Geology'],
['Physical geography', 'Geomatics'],
['Physical geography', 'Geomorphology'],
['Physical geography', 'Geophysics'],
['Physical geography', 'Glaciology'],
['Physical geography', 'Hydrology'],
['Physical geography', 'Landscape ecology'],
['Physical geography', 'Lithology'],
['Physical geography', 'Meteorology'],
['Physical geography', 'Mineralogy'],
['Physical geography', 'Oceanography'],
['Physical geography', 'Palaeogeography'],
['Physical geography', 'Palaeontology'],
['Physical geography', 'Petrology'],
['Physical geography', 'Quaternary science'],
['Physical geography', 'Soil geography'],
['Human Geography', 'Behavioural geography'],
['Human Geography', 'Cognitive geography'],
['Human Geography', 'Cultural geography'],
['Human Geography', 'Development geography'],
['Human Geography', 'Economic geography'],
['Human Geography', 'Health geography'],
['Human Geography', 'Historical geography'],
['Human Geography', 'Language geography'],
['Human Geography', 'Marketing geography'],
['Human Geography', 'Military geography'],
['Human Geography', 'Political geography'],
['Human Geography', 'Population geography'],
['Human Geography', 'Religion geography'],
['Human Geography', 'Social geography'],
['Human Geography', 'Strategic geography'],
['Human Geography', 'Time geography'],
['Human Geography', 'Tourism geography'],
['Human Geography', 'Transport geography'],
['Human Geography', 'Urban geography'],
['Cartography', 'Celestial cartography'],
['Cartography', 'Planetary cartography'],
['Cartography', 'Topography'],
['Cultural psychology', 'Asian psychology'],
['Cultural psychology', 'Black psychology'],
['Psychopathology', 'Child psychopathology'],
['Applied sociology', 'Leisure studies'],
['Applied sociology', 'Political sociology'],
['Applied sociology', 'Public sociology'],
['Applied sociology', 'Social engineering'],
['Area studies', 'African studies'],
['Area studies', 'American studies'],
['Area studies', 'Asian studies'],
['Area studies', 'Australian studies'],
['Area studies', 'European studies'],
['Area studies', 'Middle Eastern studies'],
['Behavioral sociology', 'Middle Eastern studies'],
['Collective behavior', 'Middle Eastern studies'],
['Collective behavior', 'Social movements'],
['Community informatics', 'Social network analysis'],
['Cultural studies/ethnic studies', 'Africana studies'],
['Cultural studies/ethnic studies', 'Cross-cultural studies'],
['Cultural studies/ethnic studies', 'Culturology'],
['Cultural studies/ethnic studies', 'Deaf studies'],
['Cultural studies/ethnic studies', 'Ethnology'],
['Cultural studies/ethnic studies', 'Utopian studies'],
['Cultural studies/ethnic studies', 'Whiteness studies'],
['Gender studies', 'Mens studies'],
['Gender studies', 'Womens studies'],
['Interpretive sociology', 'Ethnomethodology'],
['Interpretive sociology', 'Phenomenology'],
['Interpretive sociology', 'Social constructionism'],
['Interpretive sociology', 'Symbolic interactionism'],
['Sexology', 'Heterosexism'],
['Sexology', 'Human sexual behavior'],
['Sexology', 'Human sexuality (outline)'],
['Sexology', 'Queer studies/Queer theory'],
['Sexology', 'Sex education'],
['Social control', 'Pure sociology'],
['Social transformation', 'Computational sociology'],
['Social transformation', 'Economic sociology/Socioeconomics'],
['Anatomy', 'Comparative anatomy'],
['Anatomy', 'Human anatomy (outline)'],
['Botany (outline)', 'Ethnobotany'],
['Botany (outline)', 'Phycology'],
['Developmental biology', 'Embryology'],
['Developmental biology', 'Teratology'],
['Ecology (outline)', 'Agroecology'],
['Ecology (outline)', 'Ethnoecology'],
['Ecology (outline)', 'Human ecology'],
['Ecology (outline)', 'Landscape ecology'],
['Genetics (outline)', 'Behavioural genetics'],
['Genetics (outline)', 'Molecular genetics'],
['Genetics (outline)', 'Population genetics'],
['Microbiology', 'Bacteriology'],
['Microbiology', 'Protistology'],
['Neuroscience (outline)', 'Behavioral neuroscience'],
['Paleobiology', 'Paleontology'],
['Pathology', 'Anatomical pathology'],
['Pathology', 'Clinical pathology'],
['Pathology', 'Dermatopathology'],
['Pathology', 'Forensic pathology'],
['Pathology', 'Hematopathology'],
['Pathology', 'Histopathology'],
['Pathology', 'Molecular pathology'],
['Pathology', 'Surgical pathology'],
['Physiology', 'Human physiology'],
['Physiology', 'Exercise physiology'],
['Virology', 'Molecular virology'],
['Zoology (outline)', 'Animal communications'],
['Zoology (outline)', 'Apiology'],
['Zoology (outline)', 'Arachnology'],
['Zoology (outline)', 'Carcinology'],
['Zoology (outline)', 'Cetology'],
['Zoology (outline)', 'Entomology'],
['Zoology (outline)', 'Ethnozoology'],
['Zoology (outline)', 'Ethology'],
['Zoology (outline)', 'Helminthology'],
['Zoology (outline)', 'Herpetology'],
['Zoology (outline)', 'Ichthyology (outline)'],
['Zoology (outline)', 'Mammalogy'],
['Zoology (outline)', 'Malacology'],
['Zoology (outline)', 'Myrmecology (outline)'],
['Zoology (outline)', 'Nematology'],
['Zoology (outline)', 'Neuroethology'],
['Zoology (outline)', 'Oology'],
['Zoology (outline)', 'Ornithology (outline)'],
['Zoology (outline)', 'Planktology'],
['Zoology (outline)', 'Primatology'],
['Zoology (outline)', 'Zootomy'],
['Zoology (outline)', 'Zoosemiotics'],
['Physical geography (outline)', 'Atmospheric science / Meteorology (outline)'],
['Physical geography (outline)', 'Biogeography / Phytogeography'],
['Physical geography (outline)', 'Climatology / Paleoclimatology / Palaeogeography'],
['Physical geography (outline)', 'Coastal geography / Oceanography'],
['Physical geography (outline)', 'Edaphology / Pedology or Soil science'],
['Physical geography (outline)', 'Geobiology'],
['Physical geography (outline)', 'Geology (outline) (Geomorphology, Mineralogy, Petrology, Sedimentology, Speleology, Tectonics, Volca'],
['Physical geography (outline)', 'Geostatistics'],
['Physical geography (outline)', 'Glaciology'],
['Physical geography (outline)', 'Hydrology (outline)/ Limnology / Hydrogeology'],
['Physical geography (outline)', 'Landscape ecology'],
['Physical geography (outline)', 'Quaternary science'],
['Physical geography (outline)', 'Geophysics (outline)'],
['Physical geography (outline)', 'Paleontology'],
['Astronomy (outline)', 'Observational astronomy'],
['Astrophysics', 'Gravitational astronomy'],
['Numerical simulations', 'Astrophysical plasma'],
['Numerical simulations', 'Galaxy formation and evolution'],
['Numerical simulations', 'High-energy astrophysics'],
['Numerical simulations', 'Hydrodynamics'],
['Numerical simulations', 'Magnetohydrodynamics'],
['Numerical simulations', 'Star formation'],
['Stellar astrophysics', 'Helioseismology'],
['Stellar astrophysics', 'Stellar evolution'],
['Stellar astrophysics', 'Stellar nucleosynthesis'],
['Logic in computer science', 'Formal methods (Formal verification)'],
['Logic in computer science', 'Logic programming'],
['Logic in computer science', 'Multi-valued logic'],
['Logic in computer science', 'Programming language semantics'],
['Logic in computer science', 'Type theory'],
['Algorithms', 'Computational geometry'],
['Algorithms', 'Distributed algorithms'],
['Algorithms', 'Parallel algorithms'],
['Algorithms', 'Randomized algorithms'],
['Artificial intelligence (outline)', 'Cognitive science'],
['Artificial intelligence (outline)', 'Expert systems'],
['Artificial intelligence (outline)', 'Robotics (outline)'],
['Computer graphics', 'Image processing'],
['Computer graphics', 'Scientific visualization'],
['Computer communications (networks)', 'Cloud computing'],
['Computer communications (networks)', 'Information theory'],
['Computer communications (networks)', 'Internet, World Wide Web'],
['Computer communications (networks)', 'Ubiquitous computing'],
['Computer communications (networks)', 'Wireless computing (Mobile computing)'],
['Computer security and reliability', 'Cryptography'],
['Computer security and reliability', 'Fault-tolerant computing'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Algebraic (symbolic) computation'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computational biology (bioinformatics)'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computational chemistry'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computational mathematics'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computational neuroscience'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computational number theory'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computational physics'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Computer-aided engineering'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Numerical analysis'],
['Computing in mathematics, natural sciences, engineering, and medicine', 'Scientific computing (Computational science)'],
['Computing in social sciences, arts, humanities, and professions', 'Community informatics'],
['Computing in social sciences, arts, humanities, and professions', 'Computational economics'],
['Computing in social sciences, arts, humanities, and professions', 'Computational finance'],
['Computing in social sciences, arts, humanities, and professions', 'Computational sociology'],
['Computing in social sciences, arts, humanities, and professions', 'Digital humanities (Humanities computing)'],
['Computing in social sciences, arts, humanities, and professions', 'History of computer hardware'],
['Computing in social sciences, arts, humanities, and professions', 'History of computer science (outline)'],
['Computing in social sciences, arts, humanities, and professions', 'Humanistic informatics'],
['Computing in social sciences, arts, humanities, and professions', 'Database (outline)'],
['Computing in social sciences, arts, humanities, and professions', 'Data management'],
['Computing in social sciences, arts, humanities, and professions', 'Data mining'],
['Computing in social sciences, arts, humanities, and professions', 'Information architecture'],
['Computing in social sciences, arts, humanities, and professions', 'Information management'],
['Computing in social sciences, arts, humanities, and professions', 'Information retrieval'],
['Computing in social sciences, arts, humanities, and professions', 'Knowledge management'],
['Computing in social sciences, arts, humanities, and professions', 'Multimedia, hypermedia'],
['Computing in social sciences, arts, humanities, and professions', 'Distributed computing'],
['Computing in social sciences, arts, humanities, and professions', 'Human-computer interaction'],
['Computing in social sciences, arts, humanities, and professions', 'Operating systems'],
['Computing in social sciences, arts, humanities, and professions', 'Parallel computing'],
['Computing in social sciences, arts, humanities, and professions', 'Programming languages'],
['Computing in social sciences, arts, humanities, and professions', 'Quantum computing'],
['Computing in social sciences, arts, humanities, and professions', 'Software engineering'],
['Computing in social sciences, arts, humanities, and professions', 'Theory of computation'],
['Computing in social sciences, arts, humanities, and professions', 'VLSI design'],
['Pure Mathematics', 'Mathematical logic and Foundations of mathematics'],
['Pure Mathematics', 'Algebra (outline)'],
['Pure Mathematics', 'Analysis'],
['Pure Mathematics', 'Probability theory'],
['Pure Mathematics', 'Geometry (outline) and Topology'],
['Pure Mathematics', 'Number theory'],
['Applied Mathematics', 'Number theory'],
['Applied Mathematics', 'Approximation theory'],
['Applied Mathematics', 'Combinatorics (outline)'],
['Applied Mathematics', 'Cryptography'],
['Applied Mathematics', 'Dynamical systems'],
['Applied Mathematics', 'Game theory'],
['Applied Mathematics', 'Graph theory'],
['Applied Mathematics', 'Information theory'],
['Applied Mathematics', 'Mathematical physics'],
['Applied Mathematics', 'Numerical analysis'],
['Applied Mathematics', 'Operations research'],
['Applied Mathematics', 'Statistics (outline)'],
['Applied Mathematics', 'Theory of computation'],
['Chemical Engineering', 'Bioengineering'],
['Chemical Engineering', 'Catalysis'],
['Chemical Engineering', 'Materials engineering'],
['Chemical Engineering', 'Molecular engineering'],
['Chemical Engineering', 'Nanotechnology'],
['Chemical Engineering', 'Polymer engineering'],
['Chemical Engineering', 'Process design'],
['Chemical Engineering', 'Process engineering'],
['Chemical Engineering', 'Reaction engineering'],
['Chemical Engineering', 'Thermodynamics'],
['Chemical Engineering', 'Transport phenomena'],
['Civil Engineering', 'Coastal engineering'],
['Civil Engineering', 'Earthquake engineering'],
['Civil Engineering', 'Ecological engineering'],
['Civil Engineering', 'Environmental engineering'],
['Civil Engineering', 'Geotechnical engineering'],
['Civil Engineering', 'Hydraulic engineering'],
['Civil Engineering', 'Mining engineering'],
['Civil Engineering', 'Transportation engineering'],
['Civil Engineering', 'Structural engineering'],
['Civil Engineering', 'Structural mechanics'],
['Civil Engineering', 'Surveying'],
['', 'Distance education'],
['', 'Instructional simulation'],
['Electrical Engineering', 'Applied physics'],
['Electrical Engineering', 'Computer engineering (outline)'],
['Electrical Engineering', 'Computer science'],
['Electrical Engineering', 'Control systems engineering'],
['Electrical Engineering', 'Electronic engineering'],
['Electrical Engineering', 'Engineering physics'],
['Electrical Engineering', 'Information theory'],
['Electrical Engineering', 'Mechatronics'],
['Electrical Engineering', 'Power engineering'],
['Electrical Engineering', 'Quantum computing'],
['Electrical Engineering', 'Robotics (outline)'],
['Electrical Engineering', 'Semiconductors'],
['Electrical Engineering', 'Telecommunications engineering'],
['Materials Science and Engineering', 'Biomaterials'],
['Materials Science and Engineering', 'Ceramic engineering'],
['Materials Science and Engineering', 'Crystallography'],
['Materials Science and Engineering', 'Nanomaterials'],
['Materials Science and Engineering', 'Photonics'],
['Materials Science and Engineering', 'Physical Metallurgy'],
['Materials Science and Engineering', 'Polymer engineering'],
['Materials Science and Engineering', 'Polymer science'],
['Materials Science and Engineering', 'Semiconductors'],
['Mechanical Engineering', 'Aerospace engineering'],
['Mechanical Engineering', 'Acoustical engineering'],
['Mechanical Engineering', 'Automotive engineering'],
['Mechanical Engineering', 'Biomedical engineering'],
['Mechanical Engineering', 'Continuum mechanics'],
['Mechanical Engineering', 'Fluid mechanics'],
['Mechanical Engineering', 'Heat transfer'],
['Mechanical Engineering', 'Industrial engineering'],
['Mechanical Engineering', 'Manufacturing engineering'],
['Mechanical Engineering', 'Marine engineering'],
['Mechanical Engineering', 'Mass transfer'],
['Mechanical Engineering', 'Mechatronics'],
['Mechanical Engineering', 'Nanoengineering'],
['Mechanical Engineering', 'Ocean engineering'],
['Mechanical Engineering', 'Optical engineering'],
['Mechanical Engineering', 'Robotics'],
['Mechanical Engineering', 'Thermodynamics'],
['Systems Science', 'Chaos theory'],
['Systems Science', 'Complex systems'],
['Systems Science', 'Conceptual systems'],
['Systems Science', 'Control theory'],
['Systems Science', 'Cybernetics'],
['Systems Science', 'Network science'],
['Systems Science', 'Operations research'],
['Systems Science', 'Systems biology'],
['Systems Science', 'Computational systems biology'],
['Systems Science', 'System dynamics'],
['Systems Science', 'Systems ecology'],
['Systems Science', 'Systems engineering'],
['Systems Science', 'Systems psychology'],
['Systems Science', 'Systems theory'],
['Systems Science', 'Systems theory in anthropology'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Clinical biochemistry'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Cytogenetics'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Cytohematology'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Cytology (outline)'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Haemostasiology'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Histology'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Clinical immunology'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Clinical microbiology'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Molecular genetics'],
['Clinical laboratory sciences/Clinical pathology/Laboratory medicine', 'Parasitology'],
['Clinical physiology', 'Dentistry (outline)'],
['Clinical physiology', 'Dental hygiene and epidemiology'],
['Clinical physiology', 'Dental surgery'],
['Clinical physiology', 'Endodontics'],
['Clinical physiology', 'Implantology'],
['Clinical physiology', 'Oral and maxillofacial surgery'],
['Clinical physiology', 'Orthodontics'],
['Clinical physiology', 'Periodontics'],
['Clinical physiology', 'Prosthodontics'],
['Internal medicine', 'Cardiology'],
['Internal medicine', 'Endocrinology'],
['Internal medicine', 'Gastroenterology'],
['Internal medicine', 'Hepatology'],
['Internal medicine', 'Nephrology'],
['Internal medicine', 'Neurology'],
['Internal medicine', 'Oncology'],
['Internal medicine', 'Pulmonology'],
['Internal medicine', 'Rheumatology'],
['Ophthalmology', 'Neuro-ophthalmology'],
['Pharmaceutical sciences', 'Pharmacy'],
['Physical fitness', 'Group Fitness / aerobics'],
['Physical fitness', 'Kinesiology / Exercise science / Human performance'],
['Physical fitness', 'Personal fitness training'],
['Primary care', 'General practice'],
['Psychiatry (outline)', 'Forensic psychiatry'],
['Surgery', 'Bariatric surgery'],
['Surgery', 'Cardiothoracic surgery'],
['Surgery', 'Neurosurgery'],
['Surgery', 'Orthoptics'],
['Surgery', 'Orthopedic surgery'],
['Surgery', 'Plastic surgery'],
['Surgery', 'Trauma surgery'],
['Surgery', 'Traumatology'],
['Urology', 'Andrology'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Music'],
['Performing Arts', 'Dance'],
['Performing Arts', 'Dance'],
['Performing Arts', 'Dance'],
['Performing Arts', 'Dance'],
['Performing Arts', 'Television (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Theatre (outline)'],
['Performing Arts', 'Film (outline)'],
['Performing Arts', 'Film (outline)'],
['Performing Arts', 'Film (outline)'],
['Performing Arts', 'Film (outline)'],
['Performing Arts', 'Film (outline)'],
['Visual Arts', 'Fine Arts'],
['Visual Arts', 'Fine Arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['Visual Arts', 'Applied arts'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Ancient history'],
['History', 'Asian history'],
['History', 'Asian history'],
['History', 'Asian history'],
['History', 'Asian history'],
['History', 'History of philosophy'],
['History', 'History of philosophy'],
['History', 'History of philosophy'],
['History', 'History of philosophy'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Linguistics (Outline of linguistics)'],
['Languages and Literature', 'Creative writing'],
['Languages and Literature', 'Creative writing'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'History of literature'],
['Languages and Literature', 'World literature'],
['Languages and Literature', 'World literature'],
['Languages and Literature', 'World literature'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Civil law'],
['Law', 'Criminal law'],
['Law', 'Criminal law'],
['Law', 'Legal management'],
['Law', 'Legal management'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Philosophy', 'Applied philosophy'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Physical geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Human Geography'],
['Geography', 'Cartography'],
['Geography', 'Cartography'],
['Geography', 'Cartography'],
['Psychology', 'Cultural psychology'],
['Psychology', 'Cultural psychology'],
['Psychology', 'Psychopathology'],
['Sociology', 'Applied sociology'],
['Sociology', 'Applied sociology'],
['Sociology', 'Applied sociology'],
['Sociology', 'Applied sociology'],
['Sociology', 'Area studies'],
['Sociology', 'Area studies'],
['Sociology', 'Area studies'],
['Sociology', 'Area studies'],
['Sociology', 'Area studies'],
['Sociology', 'Area studies'],
['Sociology', 'Behavioral sociology'],
['Sociology', 'Collective behavior'],
['Sociology', 'Collective behavior'],
['Sociology', 'Community informatics'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Cultural studies/ethnic studies'],
['Sociology', 'Gender studies'],
['Sociology', 'Gender studies'],
['Sociology', 'Interpretive sociology'],
['Sociology', 'Interpretive sociology'],
['Sociology', 'Interpretive sociology'],
['Sociology', 'Interpretive sociology'],
['Sociology', 'Sexology'],
['Sociology', 'Sexology'],
['Sociology', 'Sexology'],
['Sociology', 'Sexology'],
['Sociology', 'Sexology'],
['Sociology', 'Social control'],
['Sociology', 'Social transformation'],
['Sociology', 'Social transformation'],
['Biology', 'Anatomy'],
['Biology', 'Anatomy'],
['Biology', 'Botany (outline)'],
['Biology', 'Botany (outline)'],
['Biology', 'Developmental biology'],
['Biology', 'Developmental biology'],
['Biology', 'Ecology (outline)'],
['Biology', 'Ecology (outline)'],
['Biology', 'Ecology (outline)'],
['Biology', 'Ecology (outline)'],
['Biology', 'Genetics (outline)'],
['Biology', 'Genetics (outline)'],
['Biology', 'Genetics (outline)'],
['Biology', 'Microbiology'],
['Biology', 'Microbiology'],
['Biology', 'Neuroscience (outline)'],
['Biology', 'Paleobiology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Pathology'],
['Biology', 'Physiology'],
['Biology', 'Physiology'],
['Biology', 'Virology'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Biology', 'Zoology (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Earth Science', 'Physical geography (outline)'],
['Space Sciences', 'Astronomy (outline)'],
['Space Sciences', 'Astrophysics'],
['Space Sciences', 'Numerical simulations'],
['Space Sciences', 'Numerical simulations'],
['Space Sciences', 'Numerical simulations'],
['Space Sciences', 'Numerical simulations'],
['Space Sciences', 'Numerical simulations'],
['Space Sciences', 'Numerical simulations'],
['Space Sciences', 'Stellar astrophysics'],
['Space Sciences', 'Stellar astrophysics'],
['Space Sciences', 'Stellar astrophysics'],
['Computer Science', 'Logic in computer science'],
['Computer Science', 'Logic in computer science'],
['Computer Science', 'Logic in computer science'],
['Computer Science', 'Logic in computer science'],
['Computer Science', 'Logic in computer science'],
['Computer Science', 'Algorithms'],
['Computer Science', 'Algorithms'],
['Computer Science', 'Algorithms'],
['Computer Science', 'Algorithms'],
['Computer Science', 'Artificial intelligence (outline)'],
['Computer Science', 'Artificial intelligence (outline)'],
['Computer Science', 'Artificial intelligence (outline)'],
['Computer Science', 'Computer graphics'],
['Computer Science', 'Computer graphics'],
['Computer Science', 'Computer communications (networks)'],
['Computer Science', 'Computer communications (networks)'],
['Computer Science', 'Computer communications (networks)'],
['Computer Science', 'Computer communications (networks)'],
['Computer Science', 'Computer communications (networks)'],
['Computer Science', 'Computer security and reliability'],
['Computer Science', 'Computer security and reliability'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in mathematics, natural sciences, engineering, and medicine'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Computer Science', 'Computing in social sciences, arts, humanities, and professions'],
['Mathematics', 'Pure Mathematics'],
['Mathematics', 'Pure Mathematics'],
['Mathematics', 'Pure Mathematics'],
['Mathematics', 'Pure Mathematics'],
['Mathematics', 'Pure Mathematics'],
['Mathematics', 'Pure Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Mathematics', 'Applied Mathematics'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Chemical Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', 'Civil Engineering'],
['Engineering and Technology', ''],
['Engineering and Technology', ''],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Electrical Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Materials Science and Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Mechanical Engineering'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Engineering and Technology', 'Systems Science'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical laboratory sciences/Clinical pathology/Laboratory medicine'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Clinical physiology'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Internal medicine'],
['Medicine and Health', 'Ophthalmology'],
['Medicine and Health', 'Pharmaceutical sciences'],
['Medicine and Health', 'Physical fitness'],
['Medicine and Health', 'Physical fitness'],
['Medicine and Health', 'Physical fitness'],
['Medicine and Health', 'Primary care'],
['Medicine and Health', 'Psychiatry (outline)'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Surgery'],
['Medicine and Health', 'Urology'],
['Humanities', 'Performing Arts'],
['Humanities', 'Visual Arts'],
['Humanities', 'History'],
['Humanities', 'Languages and Literature'],
['Humanities', 'Law'],
['Humanities', 'Philosophy'],
['Social Sciences', 'Anthropology'],
['Social Sciences', 'Economics'],
['Social Sciences', 'Geography'],
['Social Sciences', 'Political Science'],
['Social Sciences', 'Psychology'],
['Social Sciences', 'Sociology'],
['Social Sciences', 'Social Work'],
['Natural Sciences', 'Biology'],
['Natural Sciences', 'Chemistry'],
['Natural Sciences', 'Earth Science'],
['Natural Sciences', 'Space Sciences'],
['Natural Sciences', 'Physics'],
['Formal Sciences', 'Physics'],
['Formal Sciences', 'Computer Science'],
['Formal Sciences', 'Mathematics'],
['Applied Sciences', 'Business'],
['Applied Sciences', 'Engineering and Technology'],
['Applied Sciences', 'Medicine and Health'],
['Learning Skills Tree', ''],
['Learning Skills Tree', ''],
['Learning Skills Tree', ''],
['Learning Skills Tree', ''],
['Learning Skills Tree', '']